version: '3.8'

services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: party_escape
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_USER: myuser
    networks:
      - backend-net    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    environment:
      DATABASE_USERNAME: myuser
      DATABASE_PASSWORD: secret
      MYSQL_HOST: mysql
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - '8080:8080'
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend-net

networks:
  backend-net: